# Generated by Django 5.1 on 2025-08-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testinomial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_image', models.URLField(blank=True, null=True)),
                ('user_role', models.CharField(max_length=150)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('rivew', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
