# Generated by Django 5.1 on 2025-08-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testinomial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinomial',
            name='rivew',
            field=models.TextField(),
        ),
    ]
