# Generated by Django 5.1 on 2025-08-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_testinomial_rivew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='tittle',
            new_name='title',
        ),
    ]
