# Generated by Django 5.1 on 2025-08-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_tittle_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinomial',
            name='user_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
